name: battlecook's blog

description: This is a blog just for me. It is a blog that written the mistakes made while developing.

author: battlecook

github_username: battlecook

email: battlecook@naver.com